### ISSUE TITLE
"database is closed" error originating from `hnysqlx`

### ISSUE THREAD

**Issue by christineyen** [honeycombio/beeline-go#10]
seeing `error="sql: database is closed...  goexit"
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: sync: negative WaitGroup counter
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14c3f17]

goroutine 6937 [running]:
sync.(*WaitGroup).Add(0xc4226109a0, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.10/libexec/src/sync/waitgroup.go:73 +0x133
sync.(*WaitGroup).Done(0xc4226109a0)
	/usr/local/Cellar/go/1.10/libexec/src/sync/waitgroup.go:98 +0x34
panic(0x18282e0, 0x1e11170)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/honeycombio/hound/vendor/github.com/honeycombio/beeline-go/wrappers/hnysqlx.(*DB).NamedExec(0x0, 0x19557fd, 0x48, 0x18236e0, 0xc420c73770, 0x0, 0x0, 0x0, 0x0)
	/Users/cyen/src/go/src/github.com/honeycombio/hound/vendor/github.com/honeycombio/beeline-go/wrappers/hnysqlx/sqlx.go:345 +0x97```

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
