### ISSUE TITLE
Race in sampler hook

### ISSUE THREAD

**Issue by apechimp** [honeycombio/beeline-go#32]
When we switched to the new tracing stuff introduced in `v0.2.x`, we started seeing panics like the following.
```Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog fatal fatal error: concurrent map iteration and map write
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  goroutine 64181 [running]:
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  runtime.throw(0x12ac57f, 0x26)
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  #011/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc51d7eee90 sp=0xc51d7eee70 pc=0x42dc45
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  runtime.mapiternext(0xc51d7ef030)
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  #011/usr/local/go/src/runtime/hashmap.go:778 +0x6f1 fp=0xc51d7eef28 sp=0xc51d7eee90 pc=0x40bad1
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  github.com/launchdarkly/event-recorder/vendor/github.com/launchdarkly/foundation/honey.SamplerHook(0xc54581ffb0, 0x12901de, 0xe)
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  #011/go/src/github.com/launchdarkly/event-recorder/vendor/github.com/launchdarkly/foundation/honey/honeycomb.go:35 +0x127 fp=0xc51d7ef130 sp=0xc51d7eef28 pc=0xecfc17
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  github.com/launchdarkly/event-recorder/vendor/github.com/honeycombio/beeline-go/trace.(*Span).send(0xc4896de500)
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  #011/go/src/github.com/launchdarkly/event-recorder/vendor/github.com/honeycombio/beeline-go/trace/trace.go:328 +0x3c6 fp=0xc51d7ef278 sp=0xc51d7ef130 pc=0x753f66
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  github.com/launchdarkly/event-recorder/vendor/github.com/honeycombio/beeline-go/trace.(*Span).Send(0xc4896de500)
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  #011/go/src/github.com/launchdarkly/event-recorder/vendor/github.com/honeycombio/beeline-go/trace/trace.go:229 +0x2df fp=0xc51d7ef358 sp=0xc51d7ef278 pc=0x75366f
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  github.com/launchdarkly/event-recorder/vendor/github.com/honeycombio/beeline-go/trace.(*Span).Send(0xc4896de200)
Oct 25 10:27:49 ip-10-10-1-212 b94ce8 syslog  #011/go/src/github.com/launchdarkly/event-recorder/vendor/github.com/honeycombio/beeline-go/trace/trace.go:224 +0x2ba fp=0xc51d7ef438 sp=0xc51d7ef358 pc=0x75364a
...truncated```

Presumably, we're adding fields in another routine at the same time we're trying to send the span. That's clearly not good and I'm working to identify where we're doing this. However, I think it would be better if that error didn't cause a panic. Maybe send could acquire the same lock that is used when `AddField` is called?

**Comment by tredman** [comment]
Yikes, thanks for the report. I will look into this today.
