### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by alex** [honeycombio/beeline-go#72]
Exact cause is unclear, and I am still investigating, but I'm intermittently seeing the following crash, which I think is caused by a race condition:

```
panic: send on closed channel

goroutine 2591 [running]:
github.com/honeycombio/libhoney-go/transmission.(*Honeycomb).Add(0xc0000ab040, 0xc0022fa000)
	/home/alex/go/pkg/mod/github.com/honeycombio/libhoney-go@v1.12.0/transmission/transmission.go:127 +0x21c
github.com/honeycombio/libhoney-go.(*Event).SendPresampled(0xc0041246e0, 0x0, 0x0)
	/home/alex/go/pkg/mod/github.com/honeycombio/libhoney-go@v1.12.0/libhoney.go:806 +0x366
github.com/honeycombio/beeline-go/trace.(*Span).send(0xc003640000)
	/home/alex/go/pkg/mod/github.com/alex/beeline-go@v0.4.5-0.20190812155405-20c85e630f46/trace/trace.go:433 +0x372
github.com/honeycombio/beeline-go/trace.(*Span).sendLocked(0xc003640000)
	/home/alex/go/pkg/mod/github.com/alex/beeline-go@v0.4.5-0.20190812155405-20c85e630f46/trace/trace.go:307 +0x301
github.com/honeycombio/beeline-go/trace.(*Span).Send(0xc003640000)
	/home/alex/go/pkg/mod/github.com/alex/beeline-go@v0.4.5-0.20190812155405-20c85e630f46/trace/trace.go:252 +0x91
github.com/honeycombio/beeline-go/wrappers/common.BuildDBSpan.func1(0x0, 0x0)
	/home/alex/go/pkg/mod/github.com/alex/beeline-go@v0.4.5-0.20190812155405-20c85e630f46/wrappers/common/common.go:203 +0xf8
github.com/honeycombio/beeline-go/wrappers/hnysqlx.(*Stmt).MustExecContext(0xc000735880, 0xf54f80, 0xc002be6090, 0xc002c6e600, 0x2f, 0x2f, 0xf4ce40, 0xc003725480)
	/home/alex/go/pkg/mod/github.com/alex/beeline-go@v0.4.5-0.20190812155405-20c85e630f46/wrappers/hnysqlx/sqlx.go:1209 +0x1f0
[beyond this we're into my own code]
```

**Comment by alex** [comment]
Ugh, I'm 99% sure this bug is in our code. Will close in a few minutes if I've confirmed. Apologies for the noise!
